'use client'
import Shell from '@/components/Shell'

import Image from 'next/image'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import * as XLSX from 'xlsx'
import {supabase} from '@/lib/supabase'

const db=supabase
const money=(n:number)=>`RM ${Number(n||0).toFixed(2)}`
type Row={id:string;order_date:string;sales_area:'local'|'outstation';location:string;sales_amount:number;delivery_fee:number;delivery_quantity:number;commission:number;status:string;customer?:{customer_name?:string;phone?:string};driver?:{driver_name?:string};items?:string|null}
function exportExcel(rows:any[],filename:string,sheet:string){const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,sheet);XLSX.writeFile(wb,filename)}
function esc(v:any){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function printRows(title:string,rows:any[],columns:string[]){const w=window.open('','_blank','width=1100,height=760');if(!w)return;const head=columns.map(c=>`<th>${esc(c)}</th>`).join('');const body=rows.map(r=>`<tr>${columns.map(c=>`<td>${esc(r[c])}</td>`).join('')}</tr>`).join('');w.document.write(`<!doctype html><html><head><title>${esc(title)}</title><style>body{font-family:Arial;padding:24px;color:#222}h1{font-size:20px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #ccc;padding:7px;text-align:left}th{background:#f5f5f5}</style></head><body><h1>MONET GARDEN — ${esc(title)}</h1><p>Printed ${new Date().toLocaleString()}</p><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></body></html>`);w.document.close();w.focus();setTimeout(()=>{w.print();w.close()},250)}
function rowsFor(rows:Row[]){return rows.map(o=>({Date:o.order_date,Customer:o.customer?.customer_name||'',Phone:o.customer?.phone||'',Driver:o.driver?.driver_name||'',Area:o.location,Items:o.items||'',Boxes:o.sales_area==='outstation'?o.delivery_quantity:'', 'Delivery Fee':Number(o.delivery_fee||0),'Sales Amount':Number(o.sales_amount||0),'Driver Commission':Number(o.commission||0),Status:o.status}))}

export default function DeliveryReport(){
 const [rows,setRows]=useState<Row[]>([]),[from,setFrom]=useState(''),[to,setTo]=useState(''),[loading,setLoading]=useState(true),[user,setUser]=useState<any>(null)
 useEffect(()=>{db.auth.getUser().then(({data})=>{setUser(data.user);if(data.user)load()});const {data}=db.auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null);if(s)load()});return()=>data.subscription.unsubscribe()},[])
 async function load(){setLoading(true);const {data}=await db.from('wholesale_orders').select('*, customer:wholesale_customers(customer_name,phone), driver:drivers(driver_name)').is('deleted_at',null).order('order_date',{ascending:true});setRows((data||[]) as Row[]);setLoading(false)}
 const filtered=useMemo(()=>rows.filter(o=>(!from||o.order_date>=from)&&(!to||o.order_date<=to)),[rows,from,to])
 const local=filtered.filter(o=>o.sales_area==='local'&&o.status!=='cancelled'),out=filtered.filter(o=>o.sales_area==='outstation'&&o.status!=='cancelled')
 const localSales=local.reduce((s,o)=>s+Number(o.sales_amount||0),0),localCommission=local.reduce((s,o)=>s+Number(o.commission||0),0),localTrips=local.length
 const outSales=out.reduce((s,o)=>s+Number(o.sales_amount||0),0),outCommission=out.reduce((s,o)=>s+Number(o.commission||0),0),outBoxes=out.reduce((s,o)=>s+Number(o.delivery_quantity||0),0)
 const months=useMemo(()=>{const m=new Map<string,{localSales:number;outSales:number;localCommission:number;outCommission:number;localTrips:number;outBoxes:number}>();filtered.filter(o=>o.status!=='cancelled').forEach(o=>{const key=o.order_date.slice(0,7);const x=m.get(key)||{localSales:0,outSales:0,localCommission:0,outCommission:0,localTrips:0,outBoxes:0};if(o.sales_area==='local'){x.localSales+=Number(o.sales_amount||0);x.localCommission+=Number(o.commission||0);x.localTrips++}else{x.outSales+=Number(o.sales_amount||0);x.outCommission+=Number(o.commission||0);x.outBoxes+=Number(o.delivery_quantity||0)}m.set(key,x)});return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0]))},[filtered])
 const localRows=rowsFor(local),outRows=rowsFor(out)
 if(!user)return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:20}}><div className="card"><Image src="/logo.png" alt="MONET GARDEN" width={120} height={120}/><h1>MONET GARDEN</h1><Link className="btn primary" href="/">Back to Sign In</Link></div></main>
 return <Shell active="Delivery Report"><header className="top"><div><div className="title">Delivery Report</div><div className="sub">Local and outstation delivery performance.</div></div><Link className="btn" href="/delivery">← Delivery</Link></header>
 <section className="section card"><div className="sectionHead"><div><h2>Report Period</h2><div className="sub">Choose a date range to update the report and charts.</div></div><div className="quickBar"><label>From <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn" onClick={()=>{setFrom('');setTo('')}}>Clear</button></div></div></section>
 {loading?<div className="section card"><div className="emptyState">Loading delivery report...</div></div>:<section className="section analyticsGrid"><div className="card analyticsCard"><div className="sectionHead"><div><h2>Local Delivery</h2><div className="sub">Two key figures for the selected period.</div></div></div><div className="analyticsSummary"><div><span className="groupLabel">Total Sales Amount</span><strong>{money(localSales)}</strong></div><div><span className="groupLabel">Total Trips</span><strong>{localTrips}</strong></div><div><span className="groupLabel">Total Driver Commission</span><strong>{money(localCommission)}</strong></div></div><div className="reportChart"><div className="chartLegend"><span>Sales Amount</span><span>Driver Commission</span></div><div className="chartBars"><div className="chartBarGroup"><div className="chartBar sales" style={{height:`${Math.max(8,localSales?100:8)}%`}}/><b>{money(localSales)}</b></div><div className="chartBarGroup"><div className="chartBar fee" style={{height:`${Math.max(8,localSales?Math.min(100,(localCommission/localSales)*100):8)}%`}}/><b>{money(localCommission)}</b></div></div></div><div className="miniActions"><button className="btn" onClick={()=>printRows('Local Delivery Report',localRows,['Date','Customer','Phone','Driver','Area','Items','Boxes','Delivery Fee','Sales Amount','Driver Commission','Status'])}>Print</button><button className="btn" onClick={()=>exportExcel(localRows,'monet-garden-local-delivery-report.xlsx','Local Delivery')}>Export Excel</button></div></div>
 <div className="card analyticsCard"><div className="sectionHead"><div><h2>Outstation Delivery</h2><div className="sub">Sales and box delivery fee for the selected period.</div></div></div><div className="analyticsSummary"><div><span className="groupLabel">Total Sales Amount</span><strong>{money(outSales)}</strong></div><div><span className="groupLabel">Total Boxes</span><strong>{outBoxes}</strong></div><div><span className="groupLabel">Total Driver Commission</span><strong>{money(outCommission)}</strong></div></div><div className="reportChart"><div className="chartLegend"><span>Sales Amount</span><span>Driver Commission</span></div><div className="chartBars"><div className="chartBarGroup"><div className="chartBar sales" style={{height:`${Math.max(8,outSales?100:8)}%`}}/><b>{money(outSales)}</b></div><div className="chartBarGroup"><div className="chartBar fee" style={{height:`${Math.max(8,outSales?Math.min(100,(outCommission/outSales)*100):8)}%`}}/><b>{money(outCommission)}</b></div></div></div><div className="miniActions"><button className="btn" onClick={()=>printRows('Outstation Delivery Report',outRows,['Date','Customer','Phone','Driver','Area','Items','Boxes','Delivery Fee','Sales Amount','Driver Commission','Status'])}>Print</button><button className="btn" onClick={()=>exportExcel(outRows,'monet-garden-outstation-delivery-report.xlsx','Outstation Delivery')}>Export Excel</button></div></div></section>}
 <section className="section card"><div className="sectionHead"><div><h2>Monthly Sales</h2><div className="sub">Sales Amount is shown in RM for each month, separately for Local and Outstation.</div></div></div><div className="monthlyGrid"><div><h3>Local Sales Amount</h3><div className="monthlyChart">{months.map(([m,v])=><div className="monthCol" key={`l-${m}`}><div className="monthBar" style={{height:`${Math.max(6,Math.min(100,(v.localSales/Math.max(...months.map(x=>Math.max(x[1].localSales,x[1].outSales)),1))*100))}%`}}/><b>RM {v.localSales.toFixed(2)}</b><span>{m}</span></div>)}{!months.length&&<div className="emptyState">No data.</div>}</div></div><div><h3>Outstation Sales Amount</h3><div className="monthlyChart">{months.map(([m,v])=><div className="monthCol" key={`o-${m}`}><div className="monthBar fee" style={{height:`${Math.max(6,Math.min(100,(v.outSales/Math.max(...months.map(x=>Math.max(x[1].localSales,x[1].outSales)),1))*100))}%`}}/><b>RM {v.outSales.toFixed(2)}</b><span>{m}</span></div>)}{!months.length&&<div className="emptyState">No data.</div>}</div></div></div></section>
 <section className="section card"><div className="sectionHead"><div><h2>Delivery Details</h2><div className="sub">Cancelled records are excluded from sales totals.</div></div></div><h3>Local Delivery</h3><div className="tableWrap"><table className="table"><thead><tr><th>Date</th><th>Customer</th><th>Driver</th><th>Area</th><th>Items</th><th>Sales</th><th>Delivery Fee</th><th>Commission</th><th>Status</th></tr></thead><tbody>{local.map(o=><tr key={o.id}><td>{o.order_date}</td><td>{o.customer?.customer_name||'—'}</td><td>{o.driver?.driver_name||'—'}</td><td>{o.location}</td><td>{o.items||'—'}</td><td>{money(o.sales_amount)}</td><td>{money(o.delivery_fee)}</td><td>{money(o.commission)}</td><td>{o.status}</td></tr>)}{!local.length&&<tr><td colSpan={9}><div className="emptyState">No local records.</div></td></tr>}</tbody></table></div><h3 style={{marginTop:24}}>Outstation Delivery</h3><div className="tableWrap"><table className="table"><thead><tr><th>Date</th><th>Customer</th><th>Driver</th><th>Area</th><th>Boxes</th><th>Sales</th><th>Delivery Fee</th><th>Commission</th><th>Status</th></tr></thead><tbody>{out.map(o=><tr key={o.id}><td>{o.order_date}</td><td>{o.customer?.customer_name||'—'}</td><td>{o.driver?.driver_name||'—'}</td><td>{o.location}</td><td>{o.delivery_quantity}</td><td>{money(o.sales_amount)}</td><td>{money(o.delivery_fee)}</td><td>{money(o.commission)}</td><td>{o.status}</td></tr>)}{!out.length&&<tr><td colSpan={9}><div className="emptyState">No outstation records.</div></td></tr>}</tbody></table></div></section>
 </Shell>
}