create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade, full_name text, role text not null default 'staff' check(role in ('admin','staff')), created_at timestamptz not null default now());
create table if not exists public.florists(id uuid primary key default gen_random_uuid(), name text not null unique, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(), order_type text not null, florist_name text not null, order_date date not null, time_from time, time_to time, fulfilment text not null check(fulfilment in ('Self Pick','Delivery')), address text, amount numeric(12,2) not null default 0, wishing_card boolean not null default false, wishing_message text, reference_photo_url text, status text not null default 'confirmed' check(status in ('confirmed','cancelled','collected','delivered')), created_by uuid references auth.users(id), created_at timestamptz not null default now(), deleted_at timestamptz);
alter table public.profiles enable row level security; alter table public.florists enable row level security; alter table public.orders enable row level security;
create policy "authenticated profiles" on public.profiles for all to authenticated using (id=auth.uid()) with check(id=auth.uid());
create policy "authenticated florists" on public.florists for select to authenticated using (true); create policy "staff manage florists" on public.florists for all to authenticated using (true) with check (true);
create policy "authenticated orders" on public.orders for select to authenticated using (deleted_at is null or created_by=auth.uid()); create policy "staff insert orders" on public.orders for insert to authenticated with check(created_by=auth.uid()); create policy "staff update orders" on public.orders for update to authenticated using(true) with check(true);
insert into public.florists(name) values ('Patrick'),('Emily'),('Michelle'),('Samantha') on conflict(name) do nothing;
