'use client'
import Image from 'next/image';import Link from 'next/link';import {useEffect,useState} from 'react';import {supabase} from '@/lib/supabase'
const db=supabase
export default function DeletedDelivery(){
 const [rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 async function load(){const {data,error}=await db.from('wholesale_orders').select('*, customer:wholesale_customers(*), driver:drivers(*)').not('deleted_at','is',null).order('deleted_at',{ascending:false});if(error)setMsg(error.message);else setRows(data||[])}
 useEffect(()=>{load()},[])
 async function restore(id:string){const {error}=await db.from('wholesale_orders').update({deleted_at:null}).eq('id',id);if(error)setMsg(error.message);else{setMsg('Delivery restored.');load()}}
 async function forever(id:string){if(!window.confirm('Permanently delete this delivery? This cannot be undone.'))return;setBusy(true);const {error}=await db.from('wholesale_orders').delete().eq('id',id);setBusy(false);if(error)setMsg(error.message);else{setMsg('Delivery permanently deleted.');load()}}
 return <div className="wrap"><aside className="side"><Image src="/logo.png" alt="MONET GARDEN" width={145} height={145} className="logo"/><nav className="nav"><Link href="/">Dashboard</Link><Link href="/orders">Orders</Link><Link href="/customers">Customers</Link><Link href="/florists">Florists</Link><Link className="active" href="/delivery">Delivery</Link><Link href="/reports">Sales Report</Link></nav></aside><main className="main"><div className="top"><div><div className="title">Deleted Delivery History</div><div className="sub">Restore deleted delivery records or permanently remove them.</div></div><Link className="btn" href="/delivery">← Back to Delivery</Link></div>{msg&&<div className="msg">{msg}</div>}<div className="card"><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Date</th><th>Type</th><th>Customer</th><th>Phone</th><th>Driver</th><th>Area</th><th>Sales</th><th>Commission</th><th>Deleted</th><th>Actions</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td>{o.order_date}</td><td>{o.sales_area}</td><td>{o.customer?.customer_name||'—'}</td><td>{o.customer?.phone||'—'}</td><td>{o.driver?.driver_name||'—'}</td><td>{o.location}</td><td>RM {Number(o.sales_amount||0).toFixed(2)}</td><td>RM {Number(o.commission||0).toFixed(2)}</td><td>{o.deleted_at?new Date(o.deleted_at).toLocaleString():'—'}</td><td><div className="actionRow"><button className="primary" onClick={()=>restore(o.id)}>Restore</button><button className="danger" onClick={()=>forever(o.id)} disabled={busy}>Delete Forever</button></div></td></tr>)}{!rows.length&&<tr><td colSpan={10}><div className="emptyState">No deleted deliveries.</div></td></tr>}</tbody></table></div></div></main></div>
}
